# Generated by Django 5.2.8 on 2026-01-08 08:10

import cloudinary.models
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.validate_image_file], verbose_name='profile_image'),
        ),
    ]
