# Generated by Django 5.2.4 on 2025-07-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='no data')),
                ('city', models.CharField(default='no data', max_length=100)),
                ('landmark', models.CharField(default='no data', max_length=100)),
                ('street', models.CharField(default='no data', max_length=100)),
                ('pincode', models.BigIntegerField(default=0)),
            ],
        ),
    ]
