# Generated by Django 5.2.4 on 2025-07-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountInfo',
        ),
    ]
