# Generated by Django 5.2.4 on 2025-07-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='street',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='profile',
            field=models.ImageField(default='images/default.png', upload_to='profile_pics/'),
        ),
    ]
