# Generated by Django 5.2.8 on 2025-11-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
