# Generated by Django 5.2.8 on 2025-12-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='instructions',
        ),
    ]
