# Generated by Django 5.2.8 on 2025-11-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.BigIntegerField(),
        ),
    ]
