# Generated by Django 5.2.8 on 2025-11-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('razorpay', 'RazorPay'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
