# Generated by Django 5.2.8 on 2025-11-30 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_sku',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='orders', 
                to='products.product',
                null=True,
                blank=True
                ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.productvariant'),
        ),
    ]
