# Generated by Django 5.2.8 on 2025-12-07 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancelled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (e.g., SAVE20, WELCOME10)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the coupon offer')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10% off)', max_digits=5)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum number of times this coupon can be used (0 = unlimited)')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum uses per user (0 = unlimited)')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to use this coupon', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (optional cap)', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(help_text='Coupon valid from this date/time')),
                ('valid_until', models.DateTimeField(help_text='Coupon valid until this date/time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount amount applied', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-used_at'],
            },
        ),
    ]
