# Generated by Django 5.2.8 on 2025-11-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_subtotal_alter_order_total_amount_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_sku',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='db3adf89-98d9-42b8-89f4-fde317d127f8', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.productvariant', verbose_name='Product Variant'),
        ),
    ]
