# Generated by Django 5.2.8 on 2025-12-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('product_defective', 'Product Defective/Damaged'), ('wrong_item', 'Wrong Item Received'), ('size_issue', 'Size Not Fit'), ('color_issue', 'Color Not as Expected'), ('quality_issue', 'Quality Issue'), ('not_as_described', 'Not as Described'), ('changed_mind', 'Changed Mind'), ('duplicate_order', 'Duplicate Order'), ('late_delivery', 'Late Delivery'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
