# Generated by Django 5.2.8 on 2025-12-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('mind_changed', 'Changed My Mind'), ('wrong_product', 'Ordered Wrong Product'), ('price_issue', 'Found Better Price Elsewhere'), ('shipping_delay', 'Delivery Taking Too Long'), ('payment_issue', 'Payment Problem'), ('duplicate_order', 'Duplicate Order'), ('coupon_issue', 'Forgot to Apply Coupon'), ('other', 'Other (Please Specify)')], max_length=50, null=True),
        ),
    ]
