# Generated by Django 5.2.4 on 2025-08-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_options_address_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='Not set', max_length=15),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Not set', max_length=100),
        ),
    ]
