# Generated by Django 5.2.8 on 2025-12-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='compare_price',
        ),
    ]
