# Generated by Django 5.2.8 on 2025-12-06 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(help_text='Discount percentage (10-90)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(help_text='Discount percentage (10-90)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
