# Generated by Django 5.2.8 on 2025-12-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productreview_reviewimage_reviewvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
