<<<<<<< HEAD
# Generated by Django 5.2.8 on 2026-01-08 08:10
=======
# Generated by Django 5.2.8 on 2026-01-07 03:35
>>>>>>> deabc68 (Add pending migration files)

import cloudinary.models
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_is_deleted_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.validate_image_file], verbose_name='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.validate_image_file], verbose_name='product_images/'),
        ),
    ]
