# Generated by Django 5.2.8 on 2026-01-05 04:31

import cloudinary.models
import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_is_deleted_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.validate_image_file], verbose_name='variant_main/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.validate_image_file], verbose_name='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.validate_image_file], verbose_name='product_images/'),
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.validate_image_file], verbose_name='variant_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
