# Generated by Django 5.2.8 on 2026-01-09 05:36

import cloudinary.models
import core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_images(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductVariant = apps.get_model('products', 'ProductVariant')
    ProductImage = apps.get_model('products', 'ProductImage')
    
    # 1. Migrate Product.image to first variant's primary_image
    for product in Product.objects.all():
        if product.image:
            first_variant = ProductVariant.objects.filter(product=product).first()
            if first_variant and not first_variant.primary_image:
                first_variant.primary_image = product.image
                first_variant.save()

    # 2. Migrate ProductImage records to variants
    for img in ProductImage.objects.filter(variant__isnull=True):
        if img.product:
            first_variant = ProductVariant.objects.filter(product=img.product).first()
            if first_variant:
                img.variant = first_variant
                img.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        # First, add the new fields (nullable)
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='primary_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.validate_image_file], verbose_name='variant_images/'),
        ),
        
        # Second, perform the data migration
        migrations.RunPython(migrate_existing_images),
        
        # Finally, remove the old fields and alter any others
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[core.validators.validate_image_file], verbose_name='variant_images/'),
        ),
    ]
