# Generated by Django 5.2.8 on 2025-12-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_admintransaction_created_at_and_more'),
    ]

    operations = [
    ]
