# Generated by Django 5.2.8 on 2025-12-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransaction',
            name='payment_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admintransaction',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], max_length=200),
        ),
    ]
