# Generated by Django 5.2.8 on 2025-12-06 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_admintransaction_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Transaction ID'),
        ),
    ]
