# Generated by Django 5.2.4 on 2025-08-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card')], default='COD', max_length=20),
        ),
    ]
