# Generated by Django 5.2.4 on 2025-08-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='stock',
        ),
    ]
